//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerCheckResult) DeepCopyInto(out *APIServerCheckResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerCheckResult.
func (in *APIServerCheckResult) DeepCopy() *APIServerCheckResult {
	if in == nil {
		return nil
	}
	out := new(APIServerCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerCheckSpec) DeepCopyInto(out *APIServerCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerCheckSpec.
func (in *APIServerCheckSpec) DeepCopy() *APIServerCheckSpec {
	if in == nil {
		return nil
	}
	out := new(APIServerCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDAppDetail) DeepCopyInto(out *ArgoCDAppDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDAppDetail.
func (in *ArgoCDAppDetail) DeepCopy() *ArgoCDAppDetail {
	if in == nil {
		return nil
	}
	out := new(ArgoCDAppDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDCheckResult) DeepCopyInto(out *ArgoCDCheckResult) {
	*out = *in
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = make([]ArgoCDAppDetail, len(*in))
		copy(*out, *in)
	}
	if in.OutOfSync != nil {
		in, out := &in.OutOfSync, &out.OutOfSync
		*out = make([]ArgoCDAppDetail, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDCheckResult.
func (in *ArgoCDCheckResult) DeepCopy() *ArgoCDCheckResult {
	if in == nil {
		return nil
	}
	out := new(ArgoCDCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDCheckSpec) DeepCopyInto(out *ArgoCDCheckSpec) {
	*out = *in
	if in.AlertOn != nil {
		in, out := &in.AlertOn, &out.AlertOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDCheckSpec.
func (in *ArgoCDCheckSpec) DeepCopy() *ArgoCDCheckSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckResults) DeepCopyInto(out *CheckResults) {
	*out = *in
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(EtcdCheckResult)
		**out = **in
	}
	if in.APIServer != nil {
		in, out := &in.APIServer, &out.APIServer
		*out = new(APIServerCheckResult)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = new(NodeCheckResult)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterOperators != nil {
		in, out := &in.ClusterOperators, &out.ClusterOperators
		*out = new(ClusterOperatorCheckResult)
		(*in).DeepCopyInto(*out)
	}
	if in.MCPs != nil {
		in, out := &in.MCPs, &out.MCPs
		*out = new(MCPCheckResult)
		(*in).DeepCopyInto(*out)
	}
	if in.InfraPods != nil {
		in, out := &in.InfraPods, &out.InfraPods
		*out = new(InfraPodCheckResult)
		(*in).DeepCopyInto(*out)
	}
	if in.ArgoCD != nil {
		in, out := &in.ArgoCD, &out.ArgoCD
		*out = new(ArgoCDCheckResult)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomProjects != nil {
		in, out := &in.CustomProjects, &out.CustomProjects
		*out = new(CustomProjectCheckResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckResults.
func (in *CheckResults) DeepCopy() *CheckResults {
	if in == nil {
		return nil
	}
	out := new(CheckResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecksSpec) DeepCopyInto(out *ChecksSpec) {
	*out = *in
	out.Etcd = in.Etcd
	out.APIServer = in.APIServer
	out.Nodes = in.Nodes
	out.ClusterOperators = in.ClusterOperators
	out.MCPs = in.MCPs
	in.InfraPods.DeepCopyInto(&out.InfraPods)
	in.ArgoCD.DeepCopyInto(&out.ArgoCD)
	in.CustomProjects.DeepCopyInto(&out.CustomProjects)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecksSpec.
func (in *ChecksSpec) DeepCopy() *ChecksSpec {
	if in == nil {
		return nil
	}
	out := new(ChecksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthCheck) DeepCopyInto(out *ClusterHealthCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthCheck.
func (in *ClusterHealthCheck) DeepCopy() *ClusterHealthCheck {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterHealthCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthCheckList) DeepCopyInto(out *ClusterHealthCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterHealthCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthCheckList.
func (in *ClusterHealthCheckList) DeepCopy() *ClusterHealthCheckList {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterHealthCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthCheckSpec) DeepCopyInto(out *ClusterHealthCheckSpec) {
	*out = *in
	in.Checks.DeepCopyInto(&out.Checks)
	in.Notifications.DeepCopyInto(&out.Notifications)
	out.Reporting = in.Reporting
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthCheckSpec.
func (in *ClusterHealthCheckSpec) DeepCopy() *ClusterHealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthCheckStatus) DeepCopyInto(out *ClusterHealthCheckStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthCheckStatus.
func (in *ClusterHealthCheckStatus) DeepCopy() *ClusterHealthCheckStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthReport) DeepCopyInto(out *ClusterHealthReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthReport.
func (in *ClusterHealthReport) DeepCopy() *ClusterHealthReport {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterHealthReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthReportList) DeepCopyInto(out *ClusterHealthReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterHealthReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthReportList.
func (in *ClusterHealthReportList) DeepCopy() *ClusterHealthReportList {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterHealthReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthReportSpec) DeepCopyInto(out *ClusterHealthReportSpec) {
	*out = *in
	if in.RunTime != nil {
		in, out := &in.RunTime, &out.RunTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthReportSpec.
func (in *ClusterHealthReportSpec) DeepCopy() *ClusterHealthReportSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHealthReportStatus) DeepCopyInto(out *ClusterHealthReportStatus) {
	*out = *in
	in.Checks.DeepCopyInto(&out.Checks)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHealthReportStatus.
func (in *ClusterHealthReportStatus) DeepCopy() *ClusterHealthReportStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterHealthReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperatorCheckResult) DeepCopyInto(out *ClusterOperatorCheckResult) {
	*out = *in
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = make([]DegradedOperator, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperatorCheckResult.
func (in *ClusterOperatorCheckResult) DeepCopy() *ClusterOperatorCheckResult {
	if in == nil {
		return nil
	}
	out := new(ClusterOperatorCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperatorCheckSpec) DeepCopyInto(out *ClusterOperatorCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperatorCheckSpec.
func (in *ClusterOperatorCheckSpec) DeepCopy() *ClusterOperatorCheckSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterOperatorCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProjectCheckResult) DeepCopyInto(out *CustomProjectCheckResult) {
	*out = *in
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]CustomProjectResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProjectCheckResult.
func (in *CustomProjectCheckResult) DeepCopy() *CustomProjectCheckResult {
	if in == nil {
		return nil
	}
	out := new(CustomProjectCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProjectCheckSpec) DeepCopyInto(out *CustomProjectCheckSpec) {
	*out = *in
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]CustomProjectSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProjectCheckSpec.
func (in *CustomProjectCheckSpec) DeepCopy() *CustomProjectCheckSpec {
	if in == nil {
		return nil
	}
	out := new(CustomProjectCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProjectResult) DeepCopyInto(out *CustomProjectResult) {
	*out = *in
	if in.UnhealthyPods != nil {
		in, out := &in.UnhealthyPods, &out.UnhealthyPods
		*out = make([]UnhealthyPod, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProjectResult.
func (in *CustomProjectResult) DeepCopy() *CustomProjectResult {
	if in == nil {
		return nil
	}
	out := new(CustomProjectResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProjectSpec) DeepCopyInto(out *CustomProjectSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProjectSpec.
func (in *CustomProjectSpec) DeepCopy() *CustomProjectSpec {
	if in == nil {
		return nil
	}
	out := new(CustomProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DegradedOperator) DeepCopyInto(out *DegradedOperator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DegradedOperator.
func (in *DegradedOperator) DeepCopy() *DegradedOperator {
	if in == nil {
		return nil
	}
	out := new(DegradedOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailNotificationSpec) DeepCopyInto(out *EmailNotificationSpec) {
	*out = *in
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OnStatus != nil {
		in, out := &in.OnStatus, &out.OnStatus
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailNotificationSpec.
func (in *EmailNotificationSpec) DeepCopy() *EmailNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(EmailNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdCheckResult) DeepCopyInto(out *EtcdCheckResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdCheckResult.
func (in *EtcdCheckResult) DeepCopy() *EtcdCheckResult {
	if in == nil {
		return nil
	}
	out := new(EtcdCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdCheckSpec) DeepCopyInto(out *EtcdCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdCheckSpec.
func (in *EtcdCheckSpec) DeepCopy() *EtcdCheckSpec {
	if in == nil {
		return nil
	}
	out := new(EtcdCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraPodCheckResult) DeepCopyInto(out *InfraPodCheckResult) {
	*out = *in
	if in.UnhealthyPods != nil {
		in, out := &in.UnhealthyPods, &out.UnhealthyPods
		*out = make([]UnhealthyPod, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraPodCheckResult.
func (in *InfraPodCheckResult) DeepCopy() *InfraPodCheckResult {
	if in == nil {
		return nil
	}
	out := new(InfraPodCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraPodCheckSpec) DeepCopyInto(out *InfraPodCheckSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodSelectors != nil {
		in, out := &in.PodSelectors, &out.PodSelectors
		*out = make([]PodSelectorSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraPodCheckSpec.
func (in *InfraPodCheckSpec) DeepCopy() *InfraPodCheckSpec {
	if in == nil {
		return nil
	}
	out := new(InfraPodCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPCheckResult) DeepCopyInto(out *MCPCheckResult) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]MCPDetail, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPCheckResult.
func (in *MCPCheckResult) DeepCopy() *MCPCheckResult {
	if in == nil {
		return nil
	}
	out := new(MCPCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPCheckSpec) DeepCopyInto(out *MCPCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPCheckSpec.
func (in *MCPCheckSpec) DeepCopy() *MCPCheckSpec {
	if in == nil {
		return nil
	}
	out := new(MCPCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPDetail) DeepCopyInto(out *MCPDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPDetail.
func (in *MCPDetail) DeepCopy() *MCPDetail {
	if in == nil {
		return nil
	}
	out := new(MCPDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCheckResult) DeepCopyInto(out *NodeCheckResult) {
	*out = *in
	if in.NotReady != nil {
		in, out := &in.NotReady, &out.NotReady
		*out = make([]NodeDetail, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCheckResult.
func (in *NodeCheckResult) DeepCopy() *NodeCheckResult {
	if in == nil {
		return nil
	}
	out := new(NodeCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCheckSpec) DeepCopyInto(out *NodeCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCheckSpec.
func (in *NodeCheckSpec) DeepCopy() *NodeCheckSpec {
	if in == nil {
		return nil
	}
	out := new(NodeCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDetail) DeepCopyInto(out *NodeDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDetail.
func (in *NodeDetail) DeepCopy() *NodeDetail {
	if in == nil {
		return nil
	}
	out := new(NodeDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	in.Email.DeepCopyInto(&out.Email)
	in.Slack.DeepCopyInto(&out.Slack)
	in.Webhook.DeepCopyInto(&out.Webhook)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSpec.
func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSelectorSpec) DeepCopyInto(out *PodSelectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSelectorSpec.
func (in *PodSelectorSpec) DeepCopy() *PodSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(PodSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportingSpec) DeepCopyInto(out *ReportingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportingSpec.
func (in *ReportingSpec) DeepCopy() *ReportingSpec {
	if in == nil {
		return nil
	}
	out := new(ReportingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackNotificationSpec) DeepCopyInto(out *SlackNotificationSpec) {
	*out = *in
	out.WebhookSecretRef = in.WebhookSecretRef
	if in.OnStatus != nil {
		in, out := &in.OnStatus, &out.OnStatus
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackNotificationSpec.
func (in *SlackNotificationSpec) DeepCopy() *SlackNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(SlackNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnhealthyPod) DeepCopyInto(out *UnhealthyPod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnhealthyPod.
func (in *UnhealthyPod) DeepCopy() *UnhealthyPod {
	if in == nil {
		return nil
	}
	out := new(UnhealthyPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookNotificationSpec) DeepCopyInto(out *WebhookNotificationSpec) {
	*out = *in
	if in.OnStatus != nil {
		in, out := &in.OnStatus, &out.OnStatus
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookNotificationSpec.
func (in *WebhookNotificationSpec) DeepCopy() *WebhookNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookNotificationSpec)
	in.DeepCopyInto(out)
	return out
}
